---
# Files in group_vars dir are bound to host groups (defined in the hosts file in our case) not roles
# Variables listed here are applicable to the "tyk_servers" hosts

tyk_ip: DO NOT COMMIT ip
# dashboard and gateway can have the same domain but portal has to have a different domain
tyk_dashboard_domain: tyk-dashboard.navarik.com
tyk_gateway_domain: tyk-dashboard.navarik.com
tyk_portal_domain: tyk-portal.navarik.com
tyk_dashboard_port: 3000
tyk_gateway_port: 8080
tyk_licence_key: DO NOT COMMIT licence key
