---
# These tasks setup Keycloak:

- name: Install Java
  yum:
    name: java-1.8.0-openjdk.x86_64
    state: present

- import_tasks: enable_keycloak_services.yml

- import_tasks: start_keycloak.yml
