---
# This playbook deploys the whole application stack in this site.
#
# Ensure your private key needed to ssh to those servers is accessible
# and run the following command within the ansible directory:
#   ansible-playbook site.yml -i hosts --key-file ~/.ssh/id_rsa -v

- name: Preconditions
  hosts: local
  connection: local
  tasks:
    - name: Verify that Current User is not root
      command: /bin/false
      when: ansible_user_id == "root"

    - name: Download Keycloak
      get_url:
        url: "{{ keycloak_url }}"
        dest: /tmp/{{ keycloak_archive }}
  tags: local

- name: Apply common configuration to all nodes
  hosts: all:!local
  remote_user: root
  roles:
    - common
  tags: common

#- name: Install Docker CE
#  hosts: docker_servers
#  remote_user: root
#  roles:
#    - docker

- name: Install Tyk
  hosts: tyk_servers
  remote_user: root
  roles:
    - tyk
  tags: tyk

- name: Install Keycloak
  hosts: keycloak_servers
  remote_user: root
  roles:
    - keycloak
  tags: keycloak
