---
# This playbook deploys the whole application stack in this site.

- name: Preconditions
  hosts: local
  connection: local
  tasks:
    - name: Verify that Current User is not root
      command: /bin/false
      when: ansible_user_id == "root"

- name: Apply common configuration to all nodes
  hosts: all:!local
  remote_user: root

  roles:
    - common

#- name: Install Docker CE
#  hosts: docker_servers
#  remote_user: root

#  roles:
#    - docker

- name: Install Tyk
  hosts: tyk_servers
  remote_user: root

  roles:
    - tyk
