---
# These tasks copy .repo files to /etc/yum.repos.d/

- name: Creates the mongodb-org-3.0.repo file
  template: src=mongodb-org-3.0.repo dest=/etc/yum.repos.d/mongodb-org-3.0.repo

- name: Creates the tyk_tyk-dashboard.repo file
  template: src=tyk_tyk-dashboard.repo dest=/etc/yum.repos.d/tyk_tyk-dashboard.repo

- name: Creates the tyk_tyk-gateway.repo file
  template: src=tyk_tyk-gateway.repo dest=/etc/yum.repos.d/tyk_tyk-gateway.repo

- name: Creates the tyk_tyk-pump.repo file
  template: src=tyk_tyk-pump.repo dest=/etc/yum.repos.d/tyk_tyk-pump.repo

- name: update local cache
  command: yum -q makecache -y --disablerepo='*' --enablerepo=epel --enablerepo='tyk_tyk-dashboard' --enablerepo='tyk_tyk-gateway' --enablerepo='tyk_tyk-pump' info zabbix
